apiVersion: v1
kind: Secret
metadata:
  name: gardenlet-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
    config:
      seedConfig:
        metadata:
          name: initial-seed
        spec:
          networks:
            nodes: {{ required "seed.networks.nodes needs to be specified" .Values.baseCluster.nodeCidr }}
            pods: {{ required "seed.networks.pods needs to be specified" .Values.seed.networks.pods }}
            services: {{ required "seed.networks.services needs to be specified" .Values.seed.networks.services }}
            shootDefaults:
              pods: 100.73.0.0/16
              services: 100.88.0.0/13
          provider:
            region: {{ required "baseCluster.region needs to be specified" .Values.baseCluster.region }}
            type: {{ required "baseCluster.type needs to be specified" .Values.baseCluster.provider }}
          settings:
            excessCapacityReservation:
              enabled: false
{{- if eq .Values.baseCluster.provider "hcloud" }}
            loadBalancerServices:
              annotations:
                load-balancer.hetzner.cloud/disable-private-ingress: "true"
                load-balancer.hetzner.cloud/ipv6-disabled: "true"
{{- end }}
            verticalPodAutoscaler:
              enabled: false
