apiVersion: v1
kind: Secret
metadata:
  name: identity-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |
    staticPasswords:
    - email: {{ required "emailAddress is required" .Values.emailAddress }}
      hash: {{ index ( regexSplit ":"  (htpasswd "admin" .Values.adminPassword) -1 ) 1 }}
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
