apiVersion: v1
kind: Secret
metadata:
  name: gardenlet-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
    config:
      seedConfig:
        metadata:
          name: initial-seed 
        spec:
          networks:
            nodes: {{ .Gardenlet.SeedNodeCidr }} 
            pods: {{ .Gardenlet.SeedPodCidr }} 
            services: {{ .Gardenlet.SeedServiceCidr }} 
            shootDefaults:
              pods: 100.73.0.0/16
              services: 100.88.0.0/13
          provider:
            region: {{ .BaseCluster.Region }} 
            type: {{ .BaseCluster.Provider }} 
          settings:
            verticalPodAutoscaler:
              enabled: false # enable if your base cluster does not
