apiVersion: v1
kind: Secret
metadata:
  name: cloudprofiles-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |
    global:
      kubernetes:
        versions:
          1.24.12:
            classification: preview
      seedSelector:
        enabled: true
        selector:
          providerTypes:
            - hcloud

    hcloud:
      enabled: true
    regiocloud:
      enabled: true