name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: 23ke-default
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Setup errcheck
        run: go install github.com/kisielk/errcheck@latest

      - name: Run errcheck
        run: errcheck ./

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.1"
          install-go: false

      - name: Build
        run: go build
